    <div class="row">
        <div class="col-md col-md-offset well">
            <div class="panel-body">
                <table id="ListBuckSheet" class="display" cellspacing="0" width="100%">
                        <thead>
                        <tr>
							<th>thansactionID</th>
                            <th>thansactionDate</th>
                            <th>PO_Item</th>
                            <th>PO_Subitem</th>
                            <th>Product</th>
                            <th>PurchaseOrderID</th>              
                            <th>Description</th>
                            <th>Destination</th>
                            <th>Unit</th>
                            <th>UnitsOrdered</th>
                            <th>UnitsReceived</th>
                            <th>UnitsMRF</th>
                            <th>UnitsShrinkage</th>
                            <th>DateCreated</th>
                            <th>CreatedBy</th>
                            <th>RECEIVED_QUANTITY</th>
                            <th>RAS</th>
                            <th>PROMISE_DATE</th>
                            <th>PROMISE_DATE_F_A</th>
                            <th>BEGIN_FAB</th>
                            <th>BEGIN_FAB_F_A</th>              
                            <th>COMPLETED_FAB</th>
                            <th>COMPLETED_FAB_F_A</th>
                            <th>READY_FOR_INSPECTION</th>
                            <th>READY_FOR_INSPECTION_F_A</th>
                            <th>FINAL_INSPECTION</th>
                            <th>FINAL_INSPECTION_F_A</th>
                            <th>EXITWORKS</th>
                            <th>PORT_OF_EXPORT</th>
                            <th>SHIP_DAYS</th>
                            <th>FORECAST_DELIVERY</th>
                            <th>CrateNumber</th>
                            <th>PACKING_LIST_NUMBER</th>
                            <th>ASN_NUMBER</th>
                            <th>SCN_NUMBER</th>
                            <th>thANSPORT_MODE</th>
                            <th>BEGIN_FAB_F_A</th>
                            <th>MRR_NUMBER</th>
                            <th>POSSESSION_MRR</th>
                            <th>ACTUAL_DELIVERY_AT_SITE</th>
                            <th>UOSD</th>
                            <th>DELIVERY_DESTINATION</th>
                            <th>REMARKS</th>
                            <th>MWR_Number</th>        
                        </tr>
                        </thead>
                        <tfoot>
                            <tr>
                            <th>thansactionID</th>
                            <th>thansactionDate</th>
                            <th>PO_Item</th>
                            <th>PO_Subitem</th>
                            <th>Product</th>
                            <th>PurchaseOrderID</th>              
                            <th>Description</th>
                            <th>Destination</th>
                            <th>Unit</th>
                            <th>UnitsOrdered</th>
                            <th>UnitsReceived</th>
                            <th>UnitsMRF</th>
                            <th>UnitsShrinkage</th>
                            <th>DateCreated</th>
                            <th>CreatedBy</th>
                            <th>RECEIVED_QUANTITY</th>
                            <th>RAS</th>
                            <th>PROMISE_DATE</th>
                            <th>PROMISE_DATE_F_A</th>
                            <th>BEGIN_FAB</th>
                            <th>BEGIN_FAB_F_A</th>              
                            <th>COMPLETED_FAB</th>
                            <th>COMPLETED_FAB_F_A</th>
                            <th>READY_FOR_INSPECTION</th>
                            <th>READY_FOR_INSPECTION_F_A</th>
                            <th>FINAL_INSPECTION</th>
                            <th>FINAL_INSPECTION_F_A</th>
                            <th>EXITWORKS</th>
                            <th>PORT_OF_EXPORT</th>
                            <th>SHIP_DAYS</th>
                            <th>FORECAST_DELIVERY</th>
                            <th>CrateNumber</th>
                            <th>PACKING_LIST_NUMBER</th>
                            <th>ASN_NUMBER</th>
                            <th>SCN_NUMBER</th>
                            <th>thANSPORT_MODE</th>
                            <th>BEGIN_FAB_F_A</th>
                            <th>MRR_NUMBER</th>
                            <th>POSSESSION_MRR</th>
                            <th>ACTUAL_DELIVERY_AT_SITE</th>
                            <th>UOSD</th>
                            <th>DELIVERY_DESTINATION</th>
                            <th>REMARKS</th>
                            <th>MWR_Number</th>    
                            </tr>
                        </tfoot>
                                        <tbody>
                                                 <?php echo $DatosBuckSheet; ?>
                                        </tbody>
                </table>
            </div>
        </div>
    </div>